name: headless-shell-claude

services:
  headless-shell:
    image: chromedp/headless-shell
    container_name: headless-shell.claude
    hostname: headless-shell
    restart: always
    init: true

    network_mode: host

    shm_size: 2G

    labels:
      - com.centurylinklabs.watchtower.enable=true
